import { API_ORIGIN, API_V1_BASE_URL } from '../../config/api';

const BASE_URL = API_V1_BASE_URL;

const apiRoutes = {
    base_url: BASE_URL,
    origin: API_ORIGIN,
    invoiceThemePreview: (id) => `${API_ORIGIN}/invoice-theme/${id}`,
    invoicePreview: (id) => `${BASE_URL}/invoice/preview/${id}`,
    transactionalTemplatePreview: (id) => `${BASE_URL}/transactional-template/preview/${id}`,
    register: `${BASE_URL}/register`,
    verifyOtp: `${BASE_URL}/otp-verification`,
    resendOtp: `${BASE_URL}/resend-otp`,
    login: `${BASE_URL}/login`,
    logout: `${BASE_URL}/logout`,
    getCountries: `${BASE_URL}/countries`,
    dashboardKpi: `${BASE_URL}/dashboard/overview`,
    userData: `${BASE_URL}/user-profile`,
    updateSettings: `${BASE_URL}/user/settings/update`,
    updateUserInfo: `${BASE_URL}/user/update`,
    updateUserPassword: `${BASE_URL}/user/password/update`,
    getUserPackages: `${BASE_URL}/packages/all`,
    userPackageUpgrade: `${BASE_URL}/subscriptions/upgrade`,
    userPackageDowngrade: `${BASE_URL}/subscriptions/downgrade`,
    getBillingHistory: `${BASE_URL}/billing/get/history`,
    getBillingDetails: `${BASE_URL}/billing/get/details`,
    updateBillingDetails: `${BASE_URL}/billing/update`,
    getCurrentSubscription: `${BASE_URL}/subscriptions/current`,
    getPaymentMethods: `${BASE_URL}/billing/payment-methods`,
    createPaymentMethod: `${BASE_URL}/billing/payment-methods/add`,
    setPaymentMethodDefault: `${BASE_URL}/billing/payment-methods/set-default`,
    deletePaymentMethod: `${BASE_URL}/billing/payment-methods/delete`,
    createGroup: `${BASE_URL}/groups/create`,
    getGroups: `${BASE_URL}/groups`,
    createLead: `${BASE_URL}/leads/create`,
    getLeads: `${BASE_URL}/leads`,
    deleteLead: `${BASE_URL}/leads/delete/{id}`,
    deleteMultipleLeads: `${BASE_URL}/leads/bulk-delete`,
    importLeads: `${BASE_URL}/leads/import`,
    importLeadsStatus: `${BASE_URL}/leads/import-status`,
    createCampaign:  `${BASE_URL}/campaigns/create`,
    getAllCampaigns:  `${BASE_URL}/campaigns`,
    deleteCampaign:  `${BASE_URL}/campaigns/delete`,
    deleteMultipleCampaigns: `${BASE_URL}/campaigns/bulk-delete`,
    setCampaignStatus:  `${BASE_URL}/campaigns/status`,
    getAllTemplates: `${BASE_URL}/templates`,
    createTemplate: `${BASE_URL}/template/create`,
    deleteTemplate: `${BASE_URL}/template/delete`,
    bulkDeleteTemplates: `${BASE_URL}/template/bulk-delete`,
    getTransactionalEmails: `${BASE_URL}/transactional-emails`,
    getAllTransactionalEmailsLog: `${BASE_URL}/transactional-emails-logs`,
    processTransactionalEmails: `${BASE_URL}/process-transactional-emails`,
    getTransactionEmailTemplate: `${BASE_URL}/transactional-email-template`,
    previewTransactionTemplateInvoice: `${BASE_URL}/transaction-email-invoice-preview`,
    transactionalEmailStatus: `${BASE_URL}/transactional-emails/status`,
    getTransactionalBatches: `${BASE_URL}/transactional-emails/invoice-archives`,
    getCustomerInvoices: `${BASE_URL}/transactional-emails/invoice-history`,
    deleteMultipleTransactions: `${BASE_URL}/transactional-emails/delete-bulk`,
    getProviders: `${BASE_URL}/providers`,
    createProvider: `${BASE_URL}/providers/create`,
    deleteProviders: `${BASE_URL}/providers/delete`,
    resendAuthorization: `${BASE_URL}/providers/resend`,
    statusCheck: `${BASE_URL}/providers/statusCheck`,
    getAllInvoiceThemes: `${BASE_URL}/invoice-themes`,
    getAllUsers: `${BASE_URL}/users`,
    getUserById: (id) => `${BASE_URL}/users/${id}`,
    getUserPermissions: `${BASE_URL}/users/permissions`,
    createUser: `${BASE_URL}/users/create`,
    deleteUser: `${BASE_URL}/users/delete`,
    getAllPatients: `${BASE_URL}/patients`,
    getPatientById: `${BASE_URL}/patients/profile`,
    getPatientInvoices: `${BASE_URL}/patients/{id}/invoices`,
    getPatientInvoiceById: `${BASE_URL}/patients/{id}/invoices/{invoice_id}`,
    updatePatientPassword: `${BASE_URL}/patients/password/update`,
    createPatient: `${BASE_URL}/patients/create`,
    deletePatient: `${BASE_URL}/patients/delete`,
    getSupportKpis: `${BASE_URL}/support/dashboard-kpi`,
    getAllTickets: `${BASE_URL}/support/tickets`,
    createTicket: `${BASE_URL}/support/tickets/create`, 
    viewTicket: `${BASE_URL}/support/tickets/view`,
    replyToTicket: `${BASE_URL}/support/tickets/reply`,
    getEmailReports: `${BASE_URL}/reports/emailLog`,
    getGlobalSettings: `${BASE_URL}/settings/global`,
    getAppSettings: `${BASE_URL}/settings/app`,

    //Admin Routes
    adminDashboardOverview: `${BASE_URL}/admin/dashboard/overview`,
    getAllTenantUsers: `${BASE_URL}/admin/users`,
    getAllTenantDeletedUsers: `${BASE_URL}/admin/deleted-users`,
    createTenantUser: `${BASE_URL}/admin/users/create`,
    deleteTenantUser: `${BASE_URL}/admin/users/delete`,
    deleteTenantPermanently: `${BASE_URL}/admin/users/delete-permenantly`,
    restoreTenantUser: `${BASE_URL}/admin/users/restore`,
    userProfile: `${BASE_URL}/admin/user/profile`,
    userSecuritySettings: `${BASE_URL}/admin/user/security-settings`,
    adminUpdateUserPassword: `${BASE_URL}/admin/update-user-account-password`, 
    updateUserAccountStatus: `${BASE_URL}/admin/update-user`,
    createSystemUser: `${BASE_URL}/system-users/create`,
    getAllSubscriptions: `${BASE_URL}/subscriptions`,
    getPackages: `${BASE_URL}/admin/packages`,
    getPackageSettings: `${BASE_URL}/admin/packages/settings`,
    createUpdatePackage: `${BASE_URL}/admin/packages/process-package`,
    deletePackage: `${BASE_URL}/admin/packages/delete`,
    getUserBillingInvoices: `${BASE_URL}/billing/invoices`,
    getUserPaymentMethods: `${BASE_URL}/user/billing/payment-methods`,
    getUserBillingHistory: `${BASE_URL}/user/billing/history`,
    getUserBillingDetails: `${BASE_URL}/user/billing/details`,
    getAdminSupportKpis: `${BASE_URL}/admin/support/dashboard-kpi`,
    getAdminAllTickets: `${BASE_URL}/admin/support/tickets`,
    assignTicket: `${BASE_URL}/admin/support/tickets/assign`, 
    adminViewTicket: `${BASE_URL}/admin/support/tickets/view`,
    adminReplyToTicket: `${BASE_URL}/admin/support/tickets/reply`,
    updateTicketStatus: `${BASE_URL}/admin/support/tickets/status`,
    getAdminSystemUsers: `${BASE_URL}/system-users/get`,
    systemUserPermissions: `${BASE_URL}/system-users/permissions`,
    createUpdateSystemUser: `${BASE_URL}/system-users/createOrUpdate`,
    updateSystemUserPassword: `${BASE_URL}/system-users/password/update`, 
    deleteSystemUser: `${BASE_URL}/system-users/delete`, 
    updateBranding: `${BASE_URL}/admin/settings/branding`,
    updateSettings: `${BASE_URL}/admin/settings/update`,
    getAllSettings: `${BASE_URL}/admin/settings/retreive`,
    getAdminEmailReports: `${BASE_URL}/admin/reports/emailLog`, 
    getAdminActivityLogs: `${BASE_URL}/admin/reports/activity-logs`, 
};

export default apiRoutes;